# Generated by Django 4.2.4 on 2023-08-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_tweets', '0003_mediafileupload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediaFile',
            new_name='TweetFile',
        ),
        migrations.RenameModel(
            old_name='MediaFileUpload',
            new_name='TweetFileUpload',
        ),
    ]
