# Generated by Django 4.2.4 on 2023-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tweets', '0004_rename_mediafile_tweetfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='edit_history_tweet_ids',
            field=models.TextField(blank=True, editable=False, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id_string',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
