# Generated by Django 4.2.4 on 2023-09-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tweets', '0005_alter_tweet_edit_history_tweet_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetfile',
            name='delete_after_upload',
            field=models.BooleanField(default=False, verbose_name='Delete the file after upload'),
        ),
    ]
