# Generated by Django 4.2.4 on 2023-08-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_djangonewsissue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangonewsissue',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
