# Generated by Django 4.2.4 on 2023-08-30 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_djangonewsissue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoNewsIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('text', models.TextField(max_length=2096, null=True)),
                ('url', models.CharField(max_length=128, null=True)),
                ('category', models.CharField(max_length=32, null=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.djangonewsissue')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
