# Generated by Django 4.2.4 on 2023-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_djangonewsissueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangonewsissue',
            name='issue_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
