# Generated by Django 4.2.4 on 2023-08-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_djangonewsissue_issue_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangonewsissue',
            name='issue_url',
        ),
    ]
