# Generated by Django 4.2.4 on 2023-08-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_djangonewsissue_issue_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangonewsissue',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djangonewsissue',
            name='issue_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='djangonewsissue',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
