# Generated by Django 4.2.4 on 2023-08-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_djangonewsissue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangonewsissueitem',
            name='url_status_code',
            field=models.PositiveSmallIntegerField(default=200),
        ),
    ]
